package com.rean.config;

import com.rean.model.District;
import com.rean.repository.DistrictRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Configuration;
import org.springframework.util.StopWatch;

import javax.annotation.PostConstruct;
import java.util.Arrays;
import java.util.List;

@Slf4j
@Configuration
public class LoadDistrictData {

    private final DistrictRepository districtRepository;

    public LoadDistrictData(DistrictRepository districtRepository) {
        this.districtRepository = districtRepository;
    }


    @PostConstruct
    void loadDistricts() {
        StopWatch watch = new StopWatch();
        watch.start();
        districtRepository.saveAll(this.districts);
        watch.stop();
        log.info("Load districts {} time Elapsed: {}", this.districts.size(), watch.getTotalTimeSeconds());
    }

    List<District> districts = Arrays.asList(
            new District(0L, "0102", "មង្គលបូរី", "Mongkol Borei"),
            new District(0L, "0103", "ភ្នំស្រុក", "Phnum Srok"),
            new District(0L, "0104", "ព្រះនេត្រព្រះ", "Preah Netr Preah"),
            new District(0L, "0105", "អូរជ្រៅ", "Ou Chrov"),
            new District(0L, "0106", "សិរីសោភ័ណ", "Serei Saophoan"),
            new District(0L, "0107", "ថ្មពួក", "Thma Puok"),
            new District(0L, "0108", "ស្វាយចេក", "Svay Chek"),
            new District(0L, "0109", "ម៉ាឡៃ", "Malai"),
            new District(0L, "0110", "ប៉ោយប៉ែត", "Paoy Paet"),
            new District(0L, "0201", "បាណន់", "Banan"),
            new District(0L, "0202", "ថ្មគោល", "Thma Koul"),
            new District(0L, "0203", "បាត់ដំបង", "Battambang"),
            new District(0L, "0204", "បវេល", "Bavel"),
            new District(0L, "0205", "ឯកភ្នំ", "Aek Phnum"),
            new District(0L, "0206", "មោងឫស្សី", "Moung Ruessei"),
            new District(0L, "0207", "រតនមណ្ឌល", "Rotonak Mondol"),
            new District(0L, "0208", "សង្កែ", "Sangkae"),
            new District(0L, "0209", "សំឡូត", "Samlout"),
            new District(0L, "0210", "សំពៅលូន", "Sampov Lun"),
            new District(0L, "0211", "ភ្នំព្រឹក", "Phnum Proek"),
            new District(0L, "0212", "កំរៀង", "Kamrieng"),
            new District(0L, "0213", "គាស់ក្រឡ", "Koas Krala"),
            new District(0L, "0214", "រុក្ខគិរី", "Rukh Kiri"),
            new District(0L, "0301", "បាធាយ", "Batheay"),
            new District(0L, "0302", "ចំការលើ", "Chamkar Leu"),
            new District(0L, "0303", "ជើងព្រៃ", "Cheung Prey"),
            new District(0L, "0305", "កំពង់ចាម", "Kampong Cham"),
            new District(0L, "0306", "កំពង់សៀម", "Kampong Siem"),
            new District(0L, "0307", "កងមាស", "Kang Meas"),
            new District(0L, "0308", "កោះសូទិន", "Kaoh Soutin"),
            new District(0L, "0313", "ព្រៃឈរ", "Prey Chhor"),
            new District(0L, "0314", "ស្រីសន្ធរ", "Srei Santhor"),
            new District(0L, "0315", "ស្ទឹងត្រង់", "Stueng Trang"),
            new District(0L, "0401", "បរិបូណ៌", "Baribour"),
            new District(0L, "0402", "ជលគីរី", "Chol Kiri"),
            new District(0L, "0403", "កំពង់ឆ្នាំង", "Kampong Chhnang"),
            new District(0L, "0404", "កំពង់លែង", "Kampong Leaeng"),
            new District(0L, "0405", "កំពង់ត្រឡាច", "Kampong Tralach"),
            new District(0L, "0406", "រលាប្អៀរ", "Rolea B'ier"),
            new District(0L, "0407", "សាមគ្គីមានជ័យ", "Sameakki Mean Chey"),
            new District(0L, "0408", "ទឹកផុស", "Tuek Phos"),
            new District(0L, "0501", "បរសេដ្ឋ", "Basedth"),
            new District(0L, "0502", "ច្បារមន", "Chbar Mon"),
            new District(0L, "0503", "គងពិសី", "Kong Pisei"),
            new District(0L, "0504", "ឱរ៉ាល់", "Aoral"),
            new District(0L, "0505", "ឧដុង្គ", "Odongk"),
            new District(0L, "0506", "ភ្នំស្រួច", "Phnum Sruoch"),
            new District(0L, "0507", "សំរោងទង", "Samraong Tong"),
            new District(0L, "0508", "ថ្ពង", "Thpong"),
            new District(0L, "0601", "បារាយណ៍", "Baray"),
            new District(0L, "0602", "កំពង់ស្វាយ", "Kampong Svay"),
            new District(0L, "0603", "ស្ទឹងសែន", "Stueng Saen"),
            new District(0L, "0604", "ប្រាសាទបល្ល័ង្គ", "Prasat Ballangk"),
            new District(0L, "0605", "ប្រាសាទសំបូរ", "Prasat Sambour"),
            new District(0L, "0606", "សណ្ដាន់", "Sandan"),
            new District(0L, "0607", "សន្ទុក", "Santuk"),
            new District(0L, "0608", "ស្ទោង", "Stoung"),
            new District(0L, "0609", "តាំងគោក", "Taing Kouk"),
            new District(0L, "0701", "អង្គរជ័យ", "Angkor Chey"),
            new District(0L, "0702", "បន្ទាយមាស", "Banteay Meas"),
            new District(0L, "0703", "ឈូក", "Chhuk"),
            new District(0L, "0704", "ជុំគិរី", "Chum Kiri"),
            new District(0L, "0705", "ដងទង់", "Dang Tong"),
            new District(0L, "0706", "កំពង់ត្រាច", "Kampong Trach"),
            new District(0L, "0707", "ទឹកឈូ", "Tuek Chhou"),
            new District(0L, "0708", "កំពត", "Kampot"),
            new District(0L, "0801", "កណ្ដាលស្ទឹង", "Kandal Stueng"),
            new District(0L, "0802", "កៀនស្វាយ", "Kien Svay"),
            new District(0L, "0803", "ខ្សាច់កណ្ដាល", "Khsach Kandal"),
            new District(0L, "0804", "កោះធំ", "Kaoh Thum"),
            new District(0L, "0805", "លើកដែក", "Leuk Daek"),
            new District(0L, "0806", "ល្វាឯម", "Lvea Aem"),
            new District(0L, "0807", "មុខកំពូល", "Mukh Kampul"),
            new District(0L, "0808", "អង្គស្នួល", "Angk Snuol"),
            new District(0L, "0809", "ពញាឮ	", "Ponhea Lueu"),
            new District(0L, "0810", "ស្អាង", "S'ang"),
            new District(0L, "0811", "តាខ្មៅ", "Ta Khmau"),
            new District(0L, "0901", "បុទុមសាគរ", "Botum Sakor"),
            new District(0L, "0902", "គិរីសាគរ", "Kiri Sakor"),
            new District(0L, "0903", "កោះកុង", "Kaoh Kong"),
            new District(0L, "0904", "ខេមរភូមិន្ទ", "Khemara Phoumin"),
            new District(0L, "0905", "មណ្ឌលសីមា", "Mondol Seima"),
            new District(0L, "0906", "ស្រែអំបិល", "Srae Ambel"),
            new District(0L, "0907", "ថ្មបាំង", "Thma Bang"),
            new District(0L, "1001", "ឆ្លូង", "Chhloung"),
            new District(0L, "1002", "ក្រចេះ", "Kracheh"),
            new District(0L, "1003", "ព្រែកប្រសព្វ", "Prek Prasab"),
            new District(0L, "1004", "សំបូរ", "Sambour"),
            new District(0L, "1005", "ស្នួល", "Snuol"),
            new District(0L, "1006", "ចិត្របុរី", "Chetr Borei"),
            new District(0L, "1101", "កែវសីមា", "Kaev Seima"),
            new District(0L, "1102", "កោះញែក", "Kaoh Nheaek"),
            new District(0L, "1103", "អូររាំង", "Ou Reang"),
            new District(0L, "1104", "ពេជ្រាដា", "Pech Chreada"),
            new District(0L, "1105", "សែនមនោរម្យ", "Saen Monourom"),
            new District(0L, "1201", "ចំការមន", "Chamkar Mon"),
            new District(0L, "1202", "ដូនពេញ", "Doun Penh"),
            new District(0L, "1203", "៧មករា", "Prampir Meakkakra"),
            new District(0L, "1204", "ទួលគោក", "Tuol Kouk"),
            new District(0L, "1205", "ដង្កោ", "Dangkao"),
            new District(0L, "1206", "មានជ័យ", "Mean Chey"),
            new District(0L, "1207", "ឫស្សីកែវ", "Russey Keo"),
            new District(0L, "1208", "សែនសុខ", "Saensokh"),
            new District(0L, "1209", "ពោធិ៍សែនជ័យ", "Pur SenChey"),
            new District(0L, "1210", "ជ្រោយចង្វារ", "Chraoy Chongvar"),
            new District(0L, "1211", "ព្រែកព្នៅ", "Praek Pnov"),
            new District(0L, "1212", "ច្បារអំពៅ", "Chbar Ampov"),
            new District(0L, "1213", "បឹងកេងកង", "Boeng Keng Kang"),
            new District(0L, "1214", "កំបូល", "Kamboul"),
            new District(0L, "1301", "ជ័យសែន", "Chey Saen"),
            new District(0L, "1302", "ឆែប", "Chhaeb"),
            new District(0L, "1303", "ជាំក្សាន្ដ", "Choam Ksant"),
            new District(0L, "1304", "គូលែន", "Kuleaen"),
            new District(0L, "1305", "រវៀង", "Rovieng"),
            new District(0L, "1306", "សង្គមថ្មី", "Sangkum Thmei"),
            new District(0L, "1307", "ត្បែងមានជ័យ", "Tbaeng Mean Chey"),
            new District(0L, "1308", "ព្រះវិហារ", "Preah Vihear"),
            new District(0L, "1401", "បាភ្នំ", "Ba Phnum"),
            new District(0L, "1402", "កំចាយមារ", "Kamchay Mear"),
            new District(0L, "1403", "កំពង់ត្របែក", "Kampong Trabaek"),
            new District(0L, "1404", "កញ្ជ្រៀច", "Kanhchriech"),
            new District(0L, "1405", "មេសាង", "Me Sang"),
            new District(0L, "1406", "ពាមជរ", "Peam Chor"),
            new District(0L, "1407", "ពាមរក៍", "Peam Ro"),
            new District(0L, "1408", "ពារាំង", "Pea Reang"),
            new District(0L, "1409", "ព្រះស្ដេច", "Preah Sdach"),
            new District(0L, "1410", "ព្រៃវែង", "Prey Veng"),
            new District(0L, "1411", "ពោធិ៍រៀង", "Pur Rieng"),
            new District(0L, "1412", "ស៊ីធរកណ្ដាល", "Sithor Kandal"),
            new District(0L, "1413", "ស្វាយអន្ទរ", "Svay Antor"),
            new District(0L, "1501", "បាកាន", "Bakan"),
            new District(0L, "1502", "កណ្ដៀង", "Kandieng"),
            new District(0L, "1503", "ក្រគរ", "Krakor"),
            new District(0L, "1504", "ភ្នំក្រវ៉ាញ", "Phnum Kravanh"),
            new District(0L, "1505", "ពោធិ៍សាត់", "Pursat"),
            new District(0L, "1506", "វាលវែង", "Veal Veaeng"),
            new District(0L, "1507", "តាលោសែនជ័យ", "Ta Lou Senchey"),
            new District(0L, "1601", "អណ្ដូងមាស", "Andoung Meas"),
            new District(0L, "1602", "បានលុង", "Ban Lung"),
            new District(0L, "1603", "បរកែវ", "Bar Kaev"),
            new District(0L, "1604", "កូនមុំ", "Koun Mom"),
            new District(0L, "1605", "លំផាត់", "Lumphat"),
            new District(0L, "1606", "អូរជុំ", "Ou Chum"),
            new District(0L, "1607", "អូរយ៉ាដាវ", "Ou Ya Dav"),
            new District(0L, "1608", "តាវែង", "Ta Veaeng"),
            new District(0L, "1609", "វើនសៃ", "Veun Sai"),
            new District(0L, "1701", "អង្គរជុំ	", "Angkor Chum"),
            new District(0L, "1702", "អង្គរធំ", "Angkor Thum"),
            new District(0L, "1703", "បន្ទាយស្រី", "Banteay Srei"),
            new District(0L, "1704", "ជីក្រែង", "Chi Kraeng"),
            new District(0L, "1706", "ក្រឡាញ់", "Kralanh"),
            new District(0L, "1707", "ពួក", "Puok"),
            new District(0L, "1709", "ប្រាសាទបាគង", "Prasat Bakong"),
            new District(0L, "1710", "សៀមរាប", "Siemreap"),
            new District(0L, "1711", "សូទ្រនិគម", "Soutr Nikom"),
            new District(0L, "1712", "ស្រីស្នំ", "Srei Snam"),
            new District(0L, "1713", "ស្វាយលើ", "Svay Leu"),
            new District(0L, "1714", "វ៉ារិន", "Varin"),
            new District(0L, "1801", "ព្រះសីហនុ", "Preah Sihanouk"),
            new District(0L, "1802", "ព្រៃនប់", "Prey Nob"),
            new District(0L, "1803", "ស្ទឹងហាវ", "Stueng Hav"),
            new District(0L, "1804", "កំពង់សីលា", "Kampong Seila"),
            new District(0L, "1805", "កោះរ៉ុង", "Kaoh Rung"),
            new District(0L, "1901", "សេសាន", "Sesan"),
            new District(0L, "1902", "សៀមបូក", "Siem Bouk"),
            new District(0L, "1903", "សៀមប៉ាង", "Siem Pang"),
            new District(0L, "1904", "ស្ទឹងត្រែង", "Stung Treng"),
            new District(0L, "1905", "ថាឡាបរិវ៉ាត់", "Thala Barivat"),
            new District(0L, "1906", "បុរីអូរស្វាយសែនជ័យ", "Borei Ou Svay Senchey"),
            new District(0L, "2001", "ចន្ទ្រា", "Chantrea"),
            new District(0L, "2002", "កំពង់រោទិ៍", "Kampong Rou"),
            new District(0L, "2003", "រំដួល", "Rumduol"),
            new District(0L, "2004", "រមាសហែក", "Romeas Haek"),
            new District(0L, "2005", "ស្វាយជ្រំ", "Svay Chrum"),
            new District(0L, "2006", "ស្វាយរៀង", "Svay Rieng"),
            new District(0L, "2007", "ស្វាយទាប", "Svay Teab"),
            new District(0L, "2008", "បាវិត", "Bavet"),
            new District(0L, "2101", "អង្គរបូរី", "Angkor Borei"),
            new District(0L, "2102", "បាទី", "Bati"),
            new District(0L, "2103", "បូរីជលសារ", "Borei Cholsar"),
            new District(0L, "2104", "គីរីវង់", "Kiri Vong"),
            new District(0L, "2105", "កោះអណ្ដែត", "Kaoh Andaet"),
            new District(0L, "2106", "ព្រៃកប្បាស", "Prey Kabbas"),
            new District(0L, "2107", "សំរោង	", "Samraong"),
            new District(0L, "2108", "ដូនកែវ", "Doun Kaev"),
            new District(0L, "2109", "ត្រាំកក់", "Tram Kak"),
            new District(0L, "2110", "ទ្រាំង", "Treang"),
            new District(0L, "2201", "អន្លង់វែង", "Anlong Veaeng"),
            new District(0L, "2202", "បន្ទាយអំពិល", "Banteay Ampil"),
            new District(0L, "2203", "ចុងកាល់", "Chong Kal"),
            new District(0L, "2204", "សំរោង", "Samraong"),
            new District(0L, "2205", "ត្រពាំងប្រាសាទ", "Trapeang Prasat"),
            new District(0L, "2301", "ដំណាក់ចង្អើរ", "Damnak Chang'aeur"),
            new District(0L, "2302", "កែប", "Kaeb"),
            new District(0L, "2401", "ប៉ៃលិន", "Pailin"),
            new District(0L, "2402", "សាលាក្រៅ", "Sala Krau"),
            new District(0L, "2501", "តំបែរ", "Dambae"),
            new District(0L, "2502", "ក្រូចឆ្មារ", "Krouch Chhmar"),
            new District(0L, "2503", "មេមត់", "Memot"),
            new District(0L, "2504", "អូររាំងឪ", "Ou Reang Ov"),
            new District(0L, "2505", "ពញាក្រែក", "Ponhea Kraek"),
            new District(0L, "2506", "សួង", "Suong"),
            new District(0L, "2507", "ត្បូងឃ្មុំ", "Tboung Khmum")
    );

}
